import type { LanguagePack } from "./types";

export const en: LanguagePack = {
  id: "en",
  name: "English",
  tier: "generative",
  bcp47: "en-US",
  maxWords: 15,
  simpleMaxWords: 10,
  reactions: [
    { id: "really", text: "Really?" },
    { id: "oh-no", text: "Oh no" },
    { id: "ha", text: "Ha!" },
    { id: "mm-hmm", text: "Mm-hmm" },
    { id: "yes", text: "Yes" },
    { id: "no", text: "No" },
    { id: "thanks", text: "Thank you" },
    { id: "sorry", text: "Sorry" },
    { id: "wow", text: "Wow" },
    { id: "nice", text: "Nice" },
    { id: "agree", text: "I agree" },
    { id: "not-sure", text: "I'm not sure" },
    { id: "go-on", text: "Go on" },
    { id: "thats-great", text: "That's great" },
    { id: "oh-dear", text: "Oh dear" },
    { id: "same", text: "Same here" },
    { id: "hmm", text: "Hmm" },
    { id: "exactly", text: "Exactly" },
    { id: "wait", text: "Wait a moment" },
    { id: "typing", text: "One second, I'm typing" },
  ],
  voices: [
    { id: "af_heart", label: "Heart", description: "Warm, higher pitch, American English" },
    { id: "af_bella", label: "Bella", description: "Bright and lively, higher pitch, American English" },
    { id: "af_nicole", label: "Nicole", description: "Soft and close, like speaking quietly, American English" },
    { id: "am_michael", label: "Michael", description: "Calm, lower pitch, American English" },
    { id: "am_fenrir", label: "Fenrir", description: "Deep and steady, lower pitch, American English" },
    { id: "am_puck", label: "Puck", description: "Friendly, middle pitch, American English" },
    { id: "bf_emma", label: "Emma", description: "Clear, higher pitch, British English" },
  ],
  defaultVoice: "af_heart",
};
